<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="module_quadrotor" >

  <!-- general attribute -->
  <baselink name="fc" />
  <thrust_link name="thrust" />

  <!-- kinematics [m] -->
  <xacro:property name="rotor_x" value="0.117" />
  <xacro:property name="rotor_y" value="0.109" />
  <xacro:property name="rotor_z" value="0.036" />
  <xacro:property name="rotor_tilt" value="${pi/9}" />
  <xacro:property name="flex_link_length" value="1.1" />
  <xacro:property name="flex_joint_offset_z" value="0.03" />

  <!-- dynamics -->
  <m_f_rate value="-0.011" /> <!-- drag torque rate -->
  <xacro:property name="max_force" value="8.0" /> <!-- [N] -->
  <xacro:property name="min_force" value="0.0" /> <!-- [N] -->

  <!-- friction -->
  <xacro:macro name="damping_factor" params="link">
    <gazebo reference="main_body1">
      <dampingFactor>0.00</dampingFactor>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="extra_module" params="name parent *origin *inertial visible:=0 model_url:=1 scale:=1">
    <joint name="${parent}2${name}" type="fixed">
      <parent link="${parent}"/>
      <child link="${name}"/>
      <xacro:insert_block name="origin" />
    </joint>
    <link name="${name}">
      <xacro:insert_block name="inertial" />
      <xacro:if value="${visible == 1}">
        <visual>
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <geometry>
            <mesh filename="${model_url}" scale= "${scale} ${scale} ${scale}"/>
          </geometry>
        </visual>
      </xacro:if>
    </link>
  </xacro:macro>

  <xacro:macro name="propeller_module" params="id x y z direction tilt par_link">
    <joint name="rotor${id}" type="continuous">
      <limit effort="100.0" lower="${min_force}" upper="${max_force}" velocity="0.5"/>
      <parent link="${par_link}"/>
      <child link="thrust${id}"/>
      <origin rpy="${tilt} 0 ${-1 * direction * pi/4}" xyz="${x} ${y} ${z}"/>
      <axis xyz="0 0 ${direction}"/>
    </joint>

    <link name="thrust${id}">
      <!-- visual & collisiont -->
      <inertial>
        <origin xyz="0 0 0" rpy="${direction * 20 / pi} 0 0"/>
        <mass value="0.0091"/>
        <inertia
            ixx="0.00000807" ixy="0.0" ixz="0.0"
            iyy="0.00000807" iyz="0.0"
            izz="0.00001612"/>
      </inertial>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="package://mini_quadrotor/urdf/mesh/prop_5inch.dae" />
        </geometry>
      </visual>
    </link>
    <xacro:damping_factor link ="thrust${id}"/>

    <transmission name="rotor_tran${id}">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="rotor${id}">
        <!-- TODO: effort is torque, maybe position is enough -->
        <hardwareInterface>RotorInterface</hardwareInterface>
      </joint>
      <actuator name="rotor${id}">
        <!-- TODO: effort is torque, maybe position is enough -->
        <hardwareInterface>RotorInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

  </xacro:macro>

  <!-- dummy root link for KDL -->
  <link name="root">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.00001"/>
      <inertia
          ixx="0.000001" ixy="0.0" ixz="0.0"
          iyy="0.000001" iyz="0.0"
          izz="0.000002"/>
    </inertial>
  </link>
  <joint name="root_joint" type="fixed">
    <parent link="root"/>
    <child link="main_body1"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <!-- main_body1 -->
  <link name="main_body1">
    <inertial>
      <mass value = "0.546" />
      <origin xyz="0 0 0.012" rpy="0 0 0"/>
      <inertia
          ixx="0.0045" ixy="0" ixz="0"
          iyy="0.0045" iyz="0"
          izz="0.0082"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://mini_quadrotor/urdf/mesh/main_body.dae" />
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.28 0.28 0.168" />
      </geometry>
    </collision>
  </link>

  <link name="flex_link">
    <inertial>
      <origin xyz="${-flex_link_length/2} 0 0" rpy="0 ${pi/2} 0"/>
      <mass value="0.05"/>
      <inertia
          ixx="0.000001" ixy="0.0" ixz="0.0"
          iyy="0.000001" iyz="0.0"
          izz="0.000002"/>
    </inertial>
      <visual>
        <origin xyz="${-flex_link_length/2} 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <cylinder length="${flex_link_length}" radius="0.03"/>
        </geometry>
        <material name="green">
          <color rgba="0.0 1.0 0.0 2.0"/>
        </material>
      </visual>
  </link>

  <joint name="flex_joint1" type="fixed">
    <parent link="main_body1"/>
    <child link="flex_link"/>
    <origin rpy="0 0 0" xyz="0 0 ${-flex_joint_offset_z}"/>
    <axis xyz="1 0 0"/>
  </joint>

  <!-- main_body2 -->
  <link name="main_body2">
    <inertial>
      <mass value = "0.546" />
      <origin xyz="0 0 0.012" rpy="0 0 0"/>
      <inertia
          ixx="0.0045" ixy="0" ixz="0"
          iyy="0.0045" iyz="0"
          izz="0.0082"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://mini_quadrotor/urdf/mesh/main_body.dae" />
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.28 0.28 0.168" />
      </geometry>
    </collision>
  </link>

  <joint name="flex_joint2" type="fixed">
    <parent link="flex_link"/>
    <child link="main_body2"/>
    <origin rpy="0 0 0" xyz="${-flex_link_length} 0 ${flex_joint_offset_z}"/>
    <axis xyz="1 0 0"/>
  </joint>


  <!-- spinal -->
  <xacro:extra_module name = "fc" parent = "main_body1" visible = "0" >
    <origin xyz="-0.012 -0.003 0.023" rpy="0 0 0"/>
    <inertial>
      <mass value = "00" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0" ixy="0.0" ixz="0.0"
          iyy="0.0" iyz="0.0" izz="0.0"/>
    </inertial>
  </xacro:extra_module>

  <!-- <!-\- front realsense t265 -\-> -->
  <!-- <xacro:extra_module name = "realsense_t265" parent = "main_body" visible = "1" scale= "1" -->
  <!--                     model_url = "package://mini_quadrotor/urdf/mesh/realSense_t265.STL"> -->
  <!--   <origin xyz="0.1095 0.00775 0.0125" rpy="0 0 0"/> -->
  <!--   <inertial> -->
  <!--     <mass value = "0.07" /> -->
  <!--     <origin xyz="-0.007 -0.007 0" rpy="0 0 0"/> -->
  <!--     <inertia -->
  <!--         ixx="0.0" ixy="0.0" ixz="0.0" -->
  <!--         iyy="0.0001" iyz="0.0" -->
  <!--         izz="0.0001"/> -->
  <!--   </inertial> -->
  <!-- </xacro:extra_module> -->

  <!-- <!-\- pose frame for realsense t265 -\-> -->
  <!-- <xacro:extra_module name = "realsense_pose_frame" parent = "realsense_t265" visible = "0" > -->
  <!--   <origin xyz="-0.005 0.0 0.0" rpy="0 0 0"/> -->
  <!--   <inertial> -->
  <!--     <mass value = "0.0" /> -->
  <!--     <origin xyz="0 0 0" rpy="0 0 0"/> -->
  <!--     <inertia -->
  <!--         ixx="0.0" ixy="0.0" ixz="0.0" -->
  <!--         iyy="0.0" iyz="0.0" izz="0.0"/> -->
  <!--   </inertial> -->
  <!-- </xacro:extra_module> -->

  <!-- <!-\- battery -\-> -->
  <!-- <xacro:extra_module name = "battery" parent = "main_body" visible = "1" model_url = "package://mini_quadrotor/urdf/mesh/turnigy_3S_2200mAh.dae" > -->
  <!--   <origin xyz="0.0105 0 -0.012" rpy="0 0 0"/> -->
  <!--   <inertial> -->
  <!--     <mass value = "0.188" /> -->
  <!--     <origin xyz="0 0 0" rpy="0 0 0"/> -->
  <!--     <inertia -->
  <!--         ixx="0.0" ixy="0.0" ixz="0.0" -->
  <!--         iyy="0.0002" iyz="0.0" izz="0.0002"/> -->
  <!--   </inertial> -->
  <!-- </xacro:extra_module> -->

  <!-- propellers -->
  <xacro:propeller_module id = "1" x = "${-rotor_x}" y = "${-rotor_y}" z = "${rotor_z}" direction = "-1" tilt = "${-rotor_tilt}" par_link = "main_body1"/>
  <xacro:propeller_module id = "2" x = "${rotor_x}" y = "${-rotor_y}" z = "${rotor_z}" direction = "1" tilt = "${-rotor_tilt}" par_link = "main_body1"/>
  <xacro:propeller_module id = "3" x = "${rotor_x}" y = "${rotor_y}" z = "${rotor_z}" direction = "-1" tilt = "${rotor_tilt}" par_link = "main_body1"/>
  <xacro:propeller_module id = "4" x = "${-rotor_x}" y = "${rotor_y}" z = "${rotor_z}"  direction = "1" tilt = "${rotor_tilt}" par_link = "main_body1"/>
  <xacro:propeller_module id = "5" x = "${-rotor_x}" y = "${-rotor_y}" z = "${rotor_z}" direction = "-1" tilt = "${-rotor_tilt}" par_link = "main_body2"/>
  <xacro:propeller_module id = "6" x = "${rotor_x}" y = "${-rotor_y}" z = "${rotor_z}" direction = "1" tilt = "${-rotor_tilt}" par_link = "main_body2"/>
  <xacro:propeller_module id = "7" x = "${rotor_x}" y = "${rotor_y}" z = "${rotor_z}" direction = "-1" tilt = "${rotor_tilt}" par_link = "main_body2"/>
  <xacro:propeller_module id = "8" x = "${-rotor_x}" y = "${rotor_y}" z = "${rotor_z}"  direction = "1" tilt = "${rotor_tilt}" par_link = "main_body2"/>


</robot>
